apiVersion: v1
kind: Service
metadata:
  name: smart-feedback-service
  labels:
    app: smart-feedback-service
spec:
  type: ClusterIP
  selector:
    app: smart-feedback-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
